import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Allura, Inter, Lalezar } from "next/font/google";
import { ThemeProvider } from "./context/ThemeContext";

// font from google fonts
const inter = Inter({ subsets: ["latin"] });
const lalezar = Lalezar({ subsets: ["arabic"], weight: ["400"] });
const allura = Allura({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <h1 className={lalezar.className}>زياد احمد</h1>
          <h1 className={allura.className}>Ziad Ahmed</h1>

          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
