import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link className="active" href="/">
            Home
          </Link>
          <Link href="/posts">Posts</Link>
          <Link href="/articles">Articles</Link>
          <Link href="/users">Users</Link>
          <Link href="/users-copy">Users Copy</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
